// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_SvwP4SYrZR8c3UTOiWO7yui2IVa7S2o',
    appId: '1:900418075815:web:ade2ebbdce7359a0a86f82',
    messagingSenderId: '900418075815',
    projectId: 'recipe-flutter-4c773',
    authDomain: 'recipe-flutter-4c773.firebaseapp.com',
    storageBucket: 'recipe-flutter-4c773.firebasestorage.app',
    measurementId: 'G-1S7Z96FHDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA91PJrCtuDDjs6rQRzIEj4iQvSRn4ksJ8',
    appId: '1:900418075815:android:9ed2b055dc4dfd92a86f82',
    messagingSenderId: '900418075815',
    projectId: 'recipe-flutter-4c773',
    storageBucket: 'recipe-flutter-4c773.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL7PhO2db4iabIXyLvssDrj5tVXlsCBZQ',
    appId: '1:900418075815:ios:a0ead0cf49b5b5f7a86f82',
    messagingSenderId: '900418075815',
    projectId: 'recipe-flutter-4c773',
    storageBucket: 'recipe-flutter-4c773.firebasestorage.app',
    iosBundleId: 'com.example.projetofinalmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL7PhO2db4iabIXyLvssDrj5tVXlsCBZQ',
    appId: '1:900418075815:ios:a0ead0cf49b5b5f7a86f82',
    messagingSenderId: '900418075815',
    projectId: 'recipe-flutter-4c773',
    storageBucket: 'recipe-flutter-4c773.firebasestorage.app',
    iosBundleId: 'com.example.projetofinalmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_SvwP4SYrZR8c3UTOiWO7yui2IVa7S2o',
    appId: '1:900418075815:web:adbc05660d1780bda86f82',
    messagingSenderId: '900418075815',
    projectId: 'recipe-flutter-4c773',
    authDomain: 'recipe-flutter-4c773.firebaseapp.com',
    storageBucket: 'recipe-flutter-4c773.firebasestorage.app',
    measurementId: 'G-1GCNRTC7W9',
  );
}
